
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button rescue;

	private global::Gtk.Entry entry2;

	private global::Gtk.Label label2;

	private global::Gtk.ProgressBar progressbar1;

	private global::Gtk.Label wrong;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 500;
		this.HeightRequest = 300;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Rescue   ( •̀ᴗ•́)و ̑̑");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.Gravity = ((global::Gdk.Gravity)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rescue = new global::Gtk.Button();
		this.rescue.WidthRequest = 80;
		this.rescue.HeightRequest = 37;
		this.rescue.CanFocus = true;
		this.rescue.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.rescue.Name = "rescue";
		this.rescue.UseUnderline = true;
		this.rescue.Label = global::Mono.Unix.Catalog.GetString("Rescue");
		this.fixed1.Add(this.rescue);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rescue]));
		w1.X = 410;
		w1.Y = 256;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry();
		global::Gtk.Tooltips w2 = new Gtk.Tooltips();
		w2.SetTip(this.entry2, "Paste the password in base64 format", "Paste the password in base64 format");
		this.entry2.WidthRequest = 400;
		this.entry2.HeightRequest = 37;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add(this.entry2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
		w3.X = 10;
		w3.Y = 256;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Paste the password in base64 format");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w4.X = 12;
		w4.Y = 232;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar1 = new global::Gtk.ProgressBar();
		this.progressbar1.WidthRequest = 480;
		this.progressbar1.HeightRequest = 15;
		this.progressbar1.Name = "progressbar1";
		this.fixed1.Add(this.progressbar1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.progressbar1]));
		w5.X = 10;
		w5.Y = 212;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.wrong = new global::Gtk.Label();
		this.wrong.Name = "wrong";
		this.wrong.LabelProp = global::Mono.Unix.Catalog.GetString("(Base64 wrong format!)");
		this.fixed1.Add(this.wrong);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.wrong]));
		w6.X = 255;
		w6.Y = 232;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.rescue.Clicked += new global::System.EventHandler(this.OnRescueBtnClicked);
	}
}
